In [21]:
!pip install numpy pandas scikit-image scikit-learn tifffile trimesh shapely networkx


   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 709.8/709.8 kB 9.8 MB/s eta 0:00:00


In [48]:
!python ./classifier_rf.py \
  --wide_csv "./dataset_csvs/rbc_unified_wide.csv" \
  --long_csv "./dataset_csvs/rbc_unified_long.csv" \
  --test_size 0.2 \
  --seed 42 \
  --agg mean

[INFO] 2D training with: ./dataset_csvs/rbc_unified_wide.csv

=== [2D] Results ===
macro F1 = 0.3899
              precision    recall  f1-score   support

         SDE     0.8657    0.9667    0.9134       120
 acanthocyte     0.7500    0.8333    0.7895        18
     cluster     0.8750    0.5000    0.6364        14
  keratocyte     0.0000    0.0000    0.0000         6
   knizocyte     0.0000    0.0000    0.0000         5
 multilobate     0.0000    0.0000    0.0000         2

    accuracy                         0.8364       165
   macro avg     0.4151    0.3833    0.3899       165
weighted avg     0.7856    0.8364    0.8044       165

Confusion matrix:
 [[116   2   1   1   0   0]
 [  2  15   0   1   0   0]
 [  7   0   7   0   0   0]
 [  4   2   0   0   0   0]
 [  3   1   0   1   0   0]
 [  2   0   0   0   0   0]]

[INFO] 3D training with: ./dataset_csvs/rbc_unified_long.csv

=== [3D] Results (agg: mean ) ===
macro F1 = 0.2905
              precision    recall  f1-score   support

    

In [41]:
!python ./2D_3D_classifier_rf_lr_hgb_xgb.py \
  --wide_csv ./dataset_csvs/rbc_unified_wide.csv \
  --long_csv ./dataset_csvs/rbc_unified_long.csv \
  --model xgb \
  --save_tables


[INFO] Building 2D feature table…
[INFO] 2D table: (825, 14)
[INFO] Building 3D feature table…
[INFO] 3D table: (825, 32)
[INFO] Saved ./feature_tables/*.csv

=== [2D-only] GroupCV Results ===
macro F1 (mean±sd): 0.4859 ± 0.0255
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and bei

In [50]:
!python compare_2_d_vs_3_daug.py \
  --wide_csv /content/dataset_csvs/rbc_unified_wide.csv \
  --long_csv /content/dataset_csvs/rbc_unified_long.csv \
  --model rf --cv 5 \
  --n_aug_per_sample 5 \
  --minority_fraction 0.3


[INFO] Building 2D feature table…
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))

=== [2D-only] 

In [51]:
!python compare_2d_3d.py \
  --wide_csv /content/dataset_csvs/rbc_unified_wide.csv \
  --long_csv /content/dataset_csvs/rbc_unified_long.csv \
  --cv 5 --n_aug_per_sample 5 --minority_fraction 0.3


[INFO] Building 2D feature table…
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))

=== [2D-only] 